//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_poducts
    {
        public int id_partner_product { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> date_of_sale { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
