//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Partner_poducts = new HashSet<Partner_poducts>();
        }
    
        public int id_partner { get; set; }
        public Nullable<int> id_type_partners { get; set; }
        public string name_partners { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public string INN { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual Material_types Material_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_poducts> Partner_poducts { get; set; }
        public virtual Partners_types Partners_types { get; set; }
    }
}
